import { CountryGroupQuerySchema } from "@/schema/country";

export const countryGroupsDiscount: CountryGroupQuerySchema[] = [
  {
    id: "group-0.2-0.3",
    name: "Parity Group: 0.2-0.3",
    recommendedDiscount: 60,
    country: [
      { code: "AF", name: "Afghanistan" },
      { code: "EG", name: "Egypt" },
      { code: "IR", name: "Iran" },
      { code: "KG", name: "Kyrgyzstan" },
      { code: "LK", name: "Sri Lanka" },
      { code: "BT", name: "Bhutan" },
      { code: "LA", name: "Laos" },
      { code: "LB", name: "Lebanon" },
      { code: "LY", name: "Libya" },
      { code: "MM", name: "Myanmar" },
      { code: "PK", name: "Pakistan" },
      { code: "SL", name: "Sierra Leone" },
      { code: "TJ", name: "Tajikistan" },
      { code: "NP", name: "Nepal" },
      { code: "UZ", name: "Uzbekistan" },
      { code: "SD", name: "Sudan" },
      { code: "IN", name: "India" },
      { code: "MG", name: "Madagascar" },
      { code: "TR", name: "Turkey" },
    ],
    countryGroupDiscount: [],
  },
  {
    id: "group-0.3-0.4",
    name: "Parity Group: 0.3-0.4",
    recommendedDiscount: 50,
    country: [
      { code: "AL", name: "Albania" },
      { code: "BA", name: "Bosnia and Herzegovina" },
      { code: "CM", name: "Cameroon" },
      { code: "BD", name: "Bangladesh" },
      { code: "BF", name: "Burkina Faso" },
      { code: "BJ", name: "Benin" },
      { code: "JO", name: "Jordan" },
      { code: "BI", name: "Burundi" },
      { code: "CO", name: "Colombia" },
      { code: "CI", name: "Côte d'Ivoire" },
      { code: "FJ", name: "Fiji" },
      { code: "ET", name: "Ethiopia" },
      { code: "GE", name: "Georgia" },
      { code: "KM", name: "Comoros" },
      { code: "LS", name: "Lesotho" },
      { code: "KH", name: "Cambodia" },
      { code: "AM", name: "Armenia" },
      { code: "BO", name: "Bolivia" },
      { code: "BY", name: "Belarus" },
      { code: "DZ", name: "Algeria" },
      { code: "ER", name: "Eritrea" },
      { code: "GH", name: "Ghana" },
      { code: "GM", name: "Gambia" },
      { code: "GW", name: "Guinea-Bissau" },
      { code: "ID", name: "Indonesia" },
      { code: "KE", name: "Kenya" },
      { code: "KZ", name: "Kazakhstan" },
      { code: "MD", name: "Moldova" },
      { code: "MK", name: "North Macedonia" },
      { code: "ML", name: "Mali" },
      { code: "MW", name: "Malawi" },
      { code: "MY", name: "Malaysia" },
      { code: "MZ", name: "Mozambique" },
      { code: "NG", name: "Nigeria" },
      { code: "NI", name: "Nicaragua" },
      { code: "PH", name: "Philippines" },
      { code: "PY", name: "Paraguay" },
      { code: "RW", name: "Rwanda" },
      { code: "TH", name: "Thailand" },
      { code: "TZ", name: "Tanzania" },
      { code: "UA", name: "Ukraine" },
      { code: "UG", name: "Uganda" },
      { code: "VN", name: "Vietnam" },
      { code: "MN", name: "Mongolia" },
      { code: "MR", name: "Mauritania" },
      { code: "MU", name: "Mauritius" },
      { code: "SO", name: "Somalia" },
      { code: "TN", name: "Tunisia" },
      { code: "ZM", name: "Zambia" },
      { code: "ME", name: "Montenegro" },
      { code: "RO", name: "Romania" },
      { code: "RS", name: "Serbia" },
      { code: "SN", name: "Senegal" },
      { code: "MA", name: "Morocco" },
      { code: "NE", name: "Niger" },
      { code: "SR", name: "Suriname" },
      { code: "SZ", name: "Eswatini" },
      { code: "TG", name: "Togo" },
    ],
    countryGroupDiscount: [],
  },
  {
    id: "group-0.4-0.5",
    name: "Parity Group: 0.4-0.5",
    recommendedDiscount: 50,
    country: [
      { code: "EC", name: "Ecuador" },
      { code: "BG", name: "Bulgaria" },
      { code: "HR", name: "Croatia" },
      { code: "BW", name: "Botswana" },
      { code: "AO", name: "Angola" },
      { code: "AZ", name: "Azerbaijan" },
      { code: "CF", name: "Central African Republic" },
      { code: "CV", name: "Cabo Verde" },
      { code: "GY", name: "Guyana" },
      { code: "HU", name: "Hungary" },
      { code: "GQ", name: "Equatorial Guinea" },
      { code: "HN", name: "Honduras" },
      { code: "BH", name: "Bahrain" },
      { code: "CD", name: "Congo (the Democratic Republic of the)" },
      { code: "DO", name: "Dominican Republic" },
      { code: "GN", name: "Guinea" },
      { code: "LR", name: "Liberia" },
      { code: "PA", name: "Panama" },
      { code: "NA", name: "Namibia" },
      { code: "PE", name: "Peru" },
      { code: "PL", name: "Poland" },
      { code: "SC", name: "Seychelles" },
      { code: "SV", name: "El Salvador" },
      { code: "TW", name: "Taiwan" },
      { code: "MV", name: "Maldives" },
      { code: "TD", name: "Chad" },
      { code: "YE", name: "Yemen" },
      { code: "ZA", name: "South Africa" },
      { code: "RU", name: "Russia" },
    ],
    countryGroupDiscount: [],
  },
  {
    id: "group-0.5-0.6",
    name: "Parity Group: 0.5-0.6",
    recommendedDiscount: 40,
    country: [
      { code: "GR", name: "Greece" },
      { code: "KN", name: "Saint Kitts and Nevis" },
      { code: "AR", name: "Argentina" },
      { code: "BR", name: "Brazil" },
      { code: "CN", name: "China" },
      { code: "DJ", name: "Djibouti" },
      { code: "IQ", name: "Iraq" },
      { code: "JM", name: "Jamaica" },
      { code: "GT", name: "Guatemala" },
      { code: "LT", name: "Lithuania" },
      { code: "CL", name: "Chile" },
      { code: "CR", name: "Costa Rica" },
      { code: "CZ", name: "Czechia" },
      { code: "GA", name: "Gabon" },
      { code: "GD", name: "Grenada" },
      { code: "HT", name: "Haiti" },
      { code: "LV", name: "Latvia" },
      { code: "ST", name: "Sao Tome and Principe" },
      { code: "VC", name: "Saint Vincent and the Grenadines" },
      { code: "PT", name: "Portugal" },
      { code: "MX", name: "Mexico" },
      { code: "SA", name: "Saudi Arabia" },
      { code: "SI", name: "Slovenia" },
      { code: "SK", name: "Slovakia" },
      { code: "TM", name: "Turkmenistan" },
      { code: "BN", name: "Brunei" },
      { code: "MO", name: "Macao" },
      { code: "TL", name: "Timor-Leste" },
    ],
    countryGroupDiscount: [],
  },
  {
    id: "group-0.6-0.7",
    name: "Parity Group: 0.6-0.7",
    recommendedDiscount: 30,
    country: [
      { code: "AE", name: "United Arab Emirates" },
      { code: "ES", name: "Spain" },
      { code: "AW", name: "Aruba" },
      { code: "CY", name: "Cyprus" },
      { code: "EE", name: "Estonia" },
      { code: "IT", name: "Italy" },
      { code: "KR", name: "South Korea" },
      { code: "BZ", name: "Belize" },
      { code: "CG", name: "Congo" },
      { code: "MT", name: "Malta" },
      { code: "SG", name: "Singapore" },
      { code: "DM", name: "Dominica" },
      { code: "TO", name: "Tonga" },
      { code: "VE", name: "Venezuela" },
      { code: "WS", name: "Samoa" },
      { code: "OM", name: "Oman" },
      { code: "ZW", name: "Zimbabwe" },
    ],
    countryGroupDiscount: [],
  },
  {
    id: "group-0.7-0.8",
    name: "Parity Group: 0.7-0.8",
    recommendedDiscount: 20,
    country: [
      { code: "AT", name: "Austria" },
      { code: "JP", name: "Japan" },
      { code: "BE", name: "Belgium" },
      { code: "BS", name: "Bahamas" },
      { code: "DE", name: "Germany" },
      { code: "FR", name: "France" },
      { code: "KI", name: "Kiribati" },
      { code: "KW", name: "Kuwait" },
      { code: "HK", name: "Hong Kong" },
      { code: "LC", name: "Saint Lucia" },
      { code: "AG", name: "Antigua and Barbuda" },
      { code: "QA", name: "Qatar" },
      { code: "PG", name: "Papua New Guinea" },
      { code: "TT", name: "Trinidad and Tobago" },
      { code: "UY", name: "Uruguay" },
    ],
    countryGroupDiscount: [],
  },
  {
    id: "group-0.8-0.9",
    name: "Parity Group: 0.8-0.9",
    recommendedDiscount: 0,
    country: [
      { code: "GB", name: "United Kingdom" },
      { code: "IE", name: "Ireland" },
      { code: "LU", name: "Luxembourg" },
      { code: "FI", name: "Finland" },
      { code: "PW", name: "Palau" },
      { code: "SB", name: "Solomon Islands" },
      { code: "PR", name: "Puerto Rico" },
      { code: "NL", name: "Netherlands" },
      { code: "SE", name: "Sweden" },
      { code: "MH", name: "Marshall Islands" },
      { code: "SM", name: "San Marino" },
    ],
    countryGroupDiscount: [],
  },
  {
    id: "group-0.9-1.0",
    name: "Parity Group: 0.9-1.0",
    recommendedDiscount: 0,
    country: [
      { code: "CA", name: "Canada" },
      { code: "DK", name: "Denmark" },
      { code: "FM", name: "Micronesia (Federated States of)" },
      { code: "US", name: "United States of America" },
      { code: "SS", name: "South Sudan" },
      { code: "VU", name: "Vanuatu" },
      { code: "NO", name: "Norway" },
      { code: "NR", name: "Nauru" },
      { code: "NZ", name: "New Zealand" },
      { code: "TV", name: "Tuvalu" },
    ],
    countryGroupDiscount: [],
  },
  {
    id: "group-1.0-1.1",
    name: "Parity Group: 1.0-1.1",
    recommendedDiscount: 0,
    country: [
      { code: "AU", name: "Australia" },
      { code: "IS", name: "Iceland" },
    ],
    countryGroupDiscount: [],
  },
  {
    id: "group-1.1-1.2",
    name: "Parity Group: 1.1-1.2",
    recommendedDiscount: 0,
    country: [
      { code: "CH", name: "Switzerland" },
      { code: "IL", name: "Israel" },
      { code: "BB", name: "Barbados" },
    ],
    countryGroupDiscount: [],
  },
];
